// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhc_zhaSXmqIx7MJu59_D2itcYTKOxfpw',
    appId: '1:919211114722:web:37c2930e2dda5445bc5ebb',
    messagingSenderId: '919211114722',
    projectId: 'fireflutter-2df81',
    authDomain: 'fireflutter-2df81.firebaseapp.com',
    storageBucket: 'fireflutter-2df81.appspot.com',
    measurementId: 'G-Z32HZ23KY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nzTDv1O1KbUev9eTVNYRz2RSYXOsfXg',
    appId: '1:919211114722:android:9f71e3dbe56262f7bc5ebb',
    messagingSenderId: '919211114722',
    projectId: 'fireflutter-2df81',
    storageBucket: 'fireflutter-2df81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcF8WknoKQTk70FHe2mWWTUlT4Cob3YEY',
    appId: '1:919211114722:ios:205afc371d71ade1bc5ebb',
    messagingSenderId: '919211114722',
    projectId: 'fireflutter-2df81',
    storageBucket: 'fireflutter-2df81.appspot.com',
    iosClientId: '919211114722-h5opm5nntg6cs94o4jo5r7gfkeidv0m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcF8WknoKQTk70FHe2mWWTUlT4Cob3YEY',
    appId: '1:919211114722:ios:98311843cd722341bc5ebb',
    messagingSenderId: '919211114722',
    projectId: 'fireflutter-2df81',
    storageBucket: 'fireflutter-2df81.appspot.com',
    iosClientId: '919211114722-d6vdmnohblo19aj274fujjqd8s0o8vj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
